---

- name: Importar variables
  include_vars:
    file: /etc/ansible/roles/installAwx/vars/main.yml
    name: var

- name: Añadir ansible-playbook al PATH
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH="$PATH:/usr/local/bin/ansible-playbook"'
    create: yes
    insertafter: EOF

- name: Recargar PATH
  ansible.builtin.shell:
    cmd: source ~/.bashrc

- name: Ejecutar script de instalación de AWX
  import_playbook: "{{ awx_extract_dir }}awx-{{ awx_version }}/installer/install.yml"
  vars:
    ansible_inventory: "{{ awx_extract_dir }}awx-{{ awx_version }}/installer/inventory"

