---
- name: Instalar Docker CE
  pip:
    name: docker==6.1.3
    executable: pip
    state: present
  notify:
    - restart docker

- name: Instalar docker-compose
  pip:
    name: docker-compose
    executable: pip
    state: present
