---
#                        Tareas para instalar apache en CentOS y en Debian
#
#       <---------------------------- INSTALACIÓN DE APACHE --------------------------->

- name: Instalar http CentOS
  yum:
          name: httpd
          state: latest
  when: ansible_facts.distribution == "CentOS"

- name: Instalar httpd Debian
  apt:
          name: apache2
          state: latest
  when: ansible_facts.distribution == "Debian"

#       <------------------------- INICIAR SERVICIO APACHE ------------- -------------------->

- name: Iniciar servicio httpd CentOS
  service:
          name: httpd
          state: started
  when: ansible_facts.distribution == "CentOS"

- name: Iniciar servicio httpd Debian
  service:
          name: apache2
          state: started
  when: ansible_facts.distribution == "Debian"

#      <------------------------- ABRIR PUERTOS NECESARIOS -------------------------------------->

- name: Abrir puerto para el servicio httpd CentOS
  firewalld:
          service: http
          permanent: true
          state: enabled
  when: ansible_facts.distribution == "CentOS"

- name: Instalar ufw para Debian
  apt:
          name: ufw
          state: present
  when: ansible_facts.distribution == "Debian"

- name: Habilitar ufw
  ufw:
          state: enabled
  when: ansible_facts.distribution == "Debian"

- name: Abrir puerto 80 con ufw en Debian
  ufw:
          rule: allow
          port: "80"
  when: ansible_facts.distribution == "Debian"

- name: Abrir puerto 443 con ufw en Debian
  ufw:
          rule: allow
          port: "443"
  when: ansible_facts.distribution == "Debian"


- name: Abrir puerto 22 con ufw en Debian
  ufw:
          rule: allow
          port: "22"
  when: ansible_facts.distribution == "Debian"

#       <------------------------- REINICIAR FIREWALL --------------------------------------->

- name: Reiniciar servicio firewalld y cargar los cambios en CentOS
  service:
          name: firewalld
          state: reloaded
  when: ansible_facts.distribution == "CentOS"

- name: Reiniciar firewall y cargar los cambios en Debian
  ufw:
          state: reloaded
  when: ansible_facts.distribution == "Debian"

#       <------------------------- REINICIAR APACHE ------------------------------------------->
 
- name: Reiniciar http en CentOS
  service: 
        name: httpd
        state: restarted
  when: ansible_facts.distribution == "CentOS"


- name: Reiniciar apache en Debian 
  become: yes
  service:
          name: apache2
          state: restarted
  when: ansible_facts.distribution == "Debian"

