---
- name: Añadir repositorios para Docker CE
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/

- name: Instalar Docker CE
  dnf:
    name: docker-ce
    state: present
  notify:
    - restart docker

- name: Instalar docker-compose
  pip:
    name: docker-compose
    executable: pip3
    state: present
