---

- name: Importar Docker-CE repo
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Actualizar repositorios
  yum:
    name: '*'
    state: latest

- name: Instalar Docker-CE
  dnf:
    name: docker-ce
    state: present
  notify:
    - restart docker

- name: Instalar Docker Python
  pip:
    name: docker==6.1.3
    executable: pip
    state: present
  notify:
    - restart docker

- name: Instalar version necesaria de pyyaml
  pip:
    name: pyyaml==5.3.1
    state: present

- name: Instalar docker-compose
  pip:
    name: docker-compose
    executable: pip
    state: present
